### ISSUE TITLE
Roadmap - Board Events

### ISSUE THREAD

**Issue by vasco3** [vasco3/influx#2]
# Board Events Roadmap
## Overview

This game is a simulator to learn how Incentive Stock Options work in startup companies.
## Board events
- [x] roll dice
- [x] track months
- [x] show company stats report
- [x] show employee stats report
- [x] set employee settings
- [x] set company settings
### Company events
- [x] sales changes
- [x] gets acquired
- [x] goes IPO
- [x] goes bankrupt
- [x] gets VC funding
- [x] splits stock
- [x] gets a bank loan
### Employee events
- [x] gets fired
- [x] purchase stock
- [x] receives a paycheck
- [x] gets a job offer
- [x] gets promoted
- [x] reaches vesting cliff
